### ISSUE TITLE
背景撰写指导

### ISSUE THREAD

**Issue by snoopycat** [lingjiameng/DataMining#1]
随着市场的交易数据越来越多，对大量数据进行快速分析的需求越来越迫切。另外在一些高频交易中，依靠人发出交易指令很可能滞后导致获利机会的丢失。
为了解决这些问题，计算机技术被应用在交易中。依靠程序自动分析已有的数据，发掘套利的机会并发出交易的指令，从而获利。目前程序化交易的应用主要有如下两个方面：
1.	对基本面信息的分析，可采用程序自动分析公司财务报表之类的文件，得到该公司的资金，财务，发展状况等有价值的基本面信息帮助交易人员决策。
2.	对交易信息的分析，采用程序分析证券之间的相关性，在整个市场中寻找相关性较强的证券对，做配对交易或者分析证券的自相关性预测证券价格走势。除此之外，现在运用比较多的是根据量化人员的交易经验分析证券价格、波动的模式，得出一些均线策略，反转策略，突破策略等。
一方面，经过大规模的对数据的分析得出的判断具有更高的准确性和可信度；另一方面，程序可分析出比较抽象的模式，这些模式凭人的经验可能很难从历史数据发现。不仅如此，快速的交易指令的发出使得对高置信概率的套机机会把握的更加及时。然而，现有的程序化交易算法还有很多的不足。大多数都需要设计者有丰富的交易经验，对交易经验进行提炼，得出交易思想，然后用程序实现。这样的方式受限于交易人员的交易经验，不利于充分分析市场数据来发掘更多套利机会。

**Comment by lingjiameng** [comment]
ORZ
